trigger:
- main

pool:
  name: 'Default'

steps:
- script: echo "Validando self-hosted agent"
  displayName: 'Validar agente'

- task: UiPathPack@6
  inputs:
    projectJsonPath: 'UiPathPack@3'
    versionType: 'AutoVersion'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    outputType: 'Process'
    orchestratorConnection: 'UiPath-Orchestrator'


