trigger:
- main

pool:
  name: 'Default'   # tu agent pool

steps:

- task: UiPathPack@2
  displayName: 'Pack UiPath Project'
  inputs:
    versionType: 'AutoVersion'
    projectPath: '$(Build.SourcesDirectory)'
    outputPath: '$(Build.ArtifactStagingDirectory)'

- task: UiPathDeploy@2
  displayName: 'Deploy to UiPath Orchestrator'
  inputs:
    orchestratorConnection: 'UiPath-Automation'
    packagesPath: '$(Build.ArtifactStagingDirectory)'
    folderName: 'Servimeters/Comercio/Cartera'